[package]
name = "rust-time-memory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
time = "0.3.30"
csv = "1.3.0"
psutil = "3.2.2"
serde = "1.0.189"
serde_derive = "1.0.189"